export const GET_POKEMON = 'GET_POKEMON'
export const GET_SIDEBAR = 'GET_SIDEBAR'
export const GET_POKEMONS = 'GET_POKEMONS'
export const SET_LOADING = 'SET_LOADING'
export const SET_MENU = 'SET_MENU'